<h4>Editar grupo</h4>
<form action="" method="post" class="form-horizontal">
    <div class="control-group">
        <label class="control-label" for="inputNome">Nome</label>
        <div class="controls">
            <input type="text" id="inputNome" value="<?php echo $this->nome; ?>" name="NOME">
        </div>
    </div>
        
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-large btn-success">Cadastrar</button>
        </div>
    </div>
</form>