<ul class="breadcrumb">
    <li><a href="/admin">Início</a> <span class="divider">/</span></li>
    <li><a href="/admin/contasreceber">Contas a Pagar</a> <span class="divider">/</span></li> 
    <li class="active">Novo registro</li>
</ul>
<form action="" method="post" class="form-horizontal">
    <div class="control-group">
        <label class="control-label" for="selectStatus">Fornecedor</label>
        <div class="controls">
            <select name="ID_FORNECEDOR">
                <?php foreach($this->fornecedores as $value): ?>    
                <option value="<?php echo $value->ID; ?>"><?php echo $value->NOME; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="selectStatus">Natureza Financeira</label>
        <div class="controls">
            <select name="ID_PLANO_NATUREZA_FINANCEIRA_PAGAR">
                <?php foreach($this->naturezafinanceira as $value): ?>
                    <option value="<?php echo $value->ID; ?>"><?php echo $value->DESCRICAO; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="selectStatus">Documento de origem</label>
        <div class="controls">
            <select name="ID_DOCUMENTO_ORIGEM">
                <?php foreach($this->documentoOrigem as $value): ?>
                    <option value="<?php echo $value->ID; ?>"><?php echo $value->DESCRICAO; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="selectStatus">Total</label>
        <div class="controls">
            <input type="text" name="VALOR_TOTAL" id="valor_total">
        </div>
        <script type="text/javascript">$("#valor_total").maskMoney({symbol: 'R$ ', thousands: '.', decimal: ',', symbolStay: true});</script>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="selectStatus">Valor parcela</label>
        <div class="controls">
            <input type="text" name="VALOR" id="valor">
        </div>
        <script type="text/javascript">$("#valor").maskMoney({symbol: 'R$ ', thousands: '.', decimal: ',', symbolStay: true});</script>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="selectStatus">Status</label>
        <div class="controls">
            <select name="ID_STATUS_PARCELA">
                <?php foreach($this->status as $value): ?>
                    <option value="<?php echo $value->ID; ?>"><?php echo $value->DESCRICAO; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="selectStatus">Vencimento</label>
        <div class="controls">
            <input type="text" name="VENCIMENTO" id="valor">
        </div>
        
    </div>
    
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn">Cadastrar</button>
        </div>
    </div>
</form>