<div class="modal">

  <div class="modal-header" align="center">
      <img src="<?php echo $this->baseUrl() . '/img/logo.png'; ?>" alt="Premobel" />
    
  </div>
  <div class="modal-body">
    <form class="form-horizontal" action="" method="post">
    <div class="control-group">
    <label class="control-label" for="inputEmail">Email</label>
    <div class="controls">
      <input type="text" id="inputEmail" placeholder="Email" name="email">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputPassword">Senha</label>
    <div class="controls">
      <input type="password" id="inputPassword" placeholder="Senha" name="senha">
    </div>
  </div>
  
  </div>
  <div class="modal-footer">
    <input type="submit" class="btn btn-primary" value="Entrar" />
  </div>
    </form>
     
</div>