<script language="Javascript">
    function confirmacao(id, classe) {
        var resposta = confirm("Deseja remover esse registro?");
 
        if (resposta == true) {
            window.location.href = "<?php echo $this->baseUrl() . '/admin/pessoas/deletar/id/'; ?>"+id+'/classe/'+classe;
        }
    }
</script>
<a href="<?php echo $this->url(array('action'=>'new','controller'=>'pessoas','module'=>'admin', 'classe'=>$this->classe),null,1); ?>" class="btn btn-success"><i class="icon-ok"></i> Adicionar novo registro</a>
<table class="table table-hover">
    <thead>
        <th>Cod</th>
        <th>Nome</th>
        
        <th></th>
    </thead>
    <tbody>
        <?php 
        foreach($this->pessoas as $value): ?>
        <tr>
            <td><?php echo $value->ID; ?></td>
            <td><?php echo $value->NOME; ?>
                <?php if($this->classe == 1) : ?>
                <br>
                <a href="/admin/pessoas/historico/id/<?php echo $value->ID; ?>" title="Histórico de compras de <?php echo $value->NOME; ?>" > Histório de compras </a> | <a href="" title="Informações completas de <?php echo $value->NOME; ?>" > Informações </a>
                <?php endif; ?>
            </td>
            <td><a href="<?php echo $this->url(array('action' => 'edit', 'controller' => 'pessoas', 'module' => 'admin', 'id' => $value['ID'], 'classe'=>$this->classe), null, 1); ?>" class="btn"><i class="icon-pencil"></i> Editar</a> <a href="javascript:func()" class="btn" onClick="confirmacao(<?php echo $value['ID'].','.$this->classe; ?>)"><i class="icon-off"></i> Deletar</a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>