<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<div id="container" style="width:100%; height:400px;"></div>
<script type="text/javascript">


$(function () { 
    $('#container').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: 'Relatório de movimentação financeira'
        },
        xAxis: {
             categories: [
             <?php 
             	foreach ($this->relatorioVendas as $value) {
             		echo "'".$value->mes."/".$value->ano."', ";
             	}
             ?>

             ]
        },
        yAxis: {
            title: {
                text: 'R$'
            }
        },
        series: [
        	{
	            name: 'Vendas',
	            data: [
	            	<?php 
	             	foreach ($this->relatorioVendas as $value) {
	             		echo $value->total.", ";
	             	}
	             ?>
	            ]
        	},
        	{
	            name: 'Contas pagas',
	            data: [
	            	<?php 
	             	foreach ($this->contasPagas as $valContas) {
	             		echo $valContas->total.", ";
	             	}
	             ?>
	            ]
        	},
            {
                name: 'Contas recebidas',
                data: [
                    <?php 
                    foreach ($this->contasRecebidas as $valContasRecebidas) {
                        echo $valContasRecebidas->total.", ";
                    }
                 ?>
                ]
            },
            {
                name: 'Saídas',
                data: [
                    <?php 
                    foreach ($this->saidas as $valSaidas) {
                        echo $valSaidas->total.", ";
                    }
                 ?>
                ]
            },
            {
                name: 'Pagamentos a vista',
                data: [
                    <?php 
                    foreach ($this->aVista as $valAVista) {
                        echo $valAVista->total.", ";
                    }
                 ?>
                ]
            },
            {
                name: 'Compras',
                data: [
                    <?php 
                    foreach ($this->compras as $valCompras) {
                        echo $valCompras->totalProdutos + $valCompras->totalFrete + $valCompras->totalDespesas.", ";
                    }
                 ?>
                ]
            }
        ]
    });
});
</script>