<h4>Editar Usuário do sistema</h4>
<form action="" method="post" class="form-horizontal">
    <div class="control-group">
        <label class="control-label" for="inputNome">Nome</label>
        <div class="controls">
            <input type="text" id="inputNome" placeholder="Seu nome" name="nome" value="<?php echo $this->nome; ?>">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputEmail">Email</label>
        <div class="controls">
            <input type="text" id="inputEmail" placeholder="Email" name="email" value="<?php echo $this->email; ?>">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputPassword">Senha</label>
        <div class="controls">
            <input type="password" id="inputPassword" placeholder="Senha" name="senha">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="selectStatus">Nível de acesso</label>
        <div class="controls">
            <select name="nivel">
                <?php if($this->nivel == 1) {echo '<option value="1">Administrador</option>';} else { echo '<option value="2">Colaborador</option>'; } ?>
                <option value="1">Administrador</option>
                <option value="2">Colaborador</option>
            </select>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="selectStatus">Status</label>
        <div class="controls">
            <select name="status">
                <?php if($this->status == 1) {echo '<option value="1">Ativo</option>';} else { echo '<option value="0">Inativo</option>'; } ?>
                <option value="1">Ativo</option>
                <option value="0">Inativo</option>
            </select>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn">Editar</button> <button type="button" onClick="javascript:history.back()" class="btn">Voltar</button>
        </div>
    </div>
</form>